all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-5-85.eu-west-1.compute.internal:
      ansible_host: ec2-34-247-73-44.eu-west-1.compute.amazonaws.com
    ip-10-0-5-251.eu-west-1.compute.internal:
      ansible_host: ec2-54-75-185-173.eu-west-1.compute.amazonaws.com
    ip-10-0-10-227.eu-west-1.compute.internal:
      ansible_host: ec2-18-202-251-31.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-13-167.eu-west-1.compute.internal:
      ansible_host: ec2-54-78-234-43.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-78-234-43.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-78-234-43.eu-west-1.compute.amazonaws.com
    ip-10-0-8-45.eu-west-1.compute.internal:
      ansible_host: ec2-34-242-226-220.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-242-226-220.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-242-226-220.eu-west-1.compute.amazonaws.com
    ip-10-0-9-10.eu-west-1.compute.internal:
      ansible_host: ec2-34-243-169-63.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-243-169-63.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-243-169-63.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-14-79.eu-west-1.compute.internal:
      ansible_host: ec2-54-78-208-190.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-2-170.eu-west-1.compute.internal:
      ansible_host: ec2-34-243-246-224.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-7-137.eu-west-1.compute.internal:
      ansible_host: ec2-18-200-196-4.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-0-162.eu-west-1.compute.internal:
      ansible_host: ec2-54-195-8-19.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-2-169.eu-west-1.compute.internal:
      ansible_host: ec2-52-214-57-182.eu-west-1.compute.amazonaws.com

