all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-4-207.eu-west-1.compute.internal:
      ansible_host: ec2-34-245-84-152.eu-west-1.compute.amazonaws.com
    ip-10-0-4-53.eu-west-1.compute.internal:
      ansible_host: ec2-54-171-251-136.eu-west-1.compute.amazonaws.com
    ip-10-0-0-33.eu-west-1.compute.internal:
      ansible_host: ec2-63-34-9-112.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-4-190.eu-west-1.compute.internal:
      ansible_host: ec2-54-78-161-74.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-78-161-74.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-78-161-74.eu-west-1.compute.amazonaws.com
    ip-10-0-15-225.eu-west-1.compute.internal:
      ansible_host: ec2-54-194-220-6.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-194-220-6.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-194-220-6.eu-west-1.compute.amazonaws.com
    ip-10-0-6-157.eu-west-1.compute.internal:
      ansible_host: ec2-54-77-16-202.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-77-16-202.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-77-16-202.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-15-205.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-72-22.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-9-87.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-180-108.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-14-167.eu-west-1.compute.internal:
      ansible_host: ec2-18-202-249-50.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-4-196.eu-west-1.compute.internal:
      ansible_host: ec2-54-170-58-156.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-11-193.eu-west-1.compute.internal:
      ansible_host: ec2-54-74-216-34.eu-west-1.compute.amazonaws.com

