all:
  vars:
    ansible_become: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-10-70.eu-west-1.compute.internal:
      ansible_host: ec2-34-241-115-198.eu-west-1.compute.amazonaws.com
    ip-10-0-11-40.eu-west-1.compute.internal:
      ansible_host: ec2-63-35-180-58.eu-west-1.compute.amazonaws.com
    ip-10-0-11-120.eu-west-1.compute.internal:
      ansible_host: ec2-46-137-15-122.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-1-57.eu-west-1.compute.internal:
      ansible_host: ec2-63-35-227-78.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-63-35-227-78.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-63-35-227-78.eu-west-1.compute.amazonaws.com
    ip-10-0-14-45.eu-west-1.compute.internal:
      ansible_host: ec2-34-252-119-24.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-252-119-24.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-252-119-24.eu-west-1.compute.amazonaws.com
    ip-10-0-5-177.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-90-7.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-244-90-7.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-244-90-7.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-9-165.eu-west-1.compute.internal:
      ansible_host: ec2-3-248-228-155.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-11-253.eu-west-1.compute.internal:
      ansible_host: ec2-54-229-33-158.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-10-80.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-196-115.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-15-129.eu-west-1.compute.internal:
      ansible_host: ec2-54-74-226-78.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-6-183.eu-west-1.compute.internal:
      ansible_host: ec2-54-77-28-184.eu-west-1.compute.amazonaws.com

