all:
  vars:
    ansible_become: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-2-158.eu-west-1.compute.internal:
      ansible_host: ec2-54-194-46-254.eu-west-1.compute.amazonaws.com
    ip-10-0-6-233.eu-west-1.compute.internal:
      ansible_host: ec2-54-77-69-245.eu-west-1.compute.amazonaws.com
    ip-10-0-4-35.eu-west-1.compute.internal:
      ansible_host: ec2-63-33-192-24.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-10-204.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-215-31.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-3-249-215-31.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-3-249-215-31.eu-west-1.compute.amazonaws.com
    ip-10-0-15-252.eu-west-1.compute.internal:
      ansible_host: ec2-34-243-90-159.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-243-90-159.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-243-90-159.eu-west-1.compute.amazonaws.com
    ip-10-0-13-196.eu-west-1.compute.internal:
      ansible_host: ec2-52-215-29-122.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-215-29-122.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-215-29-122.eu-west-1.compute.amazonaws.com
    ip-10-0-14-2.eu-west-1.compute.internal:
      ansible_host: ec2-63-35-230-209.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-63-35-230-209.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-63-35-230-209.eu-west-1.compute.amazonaws.com
    ip-10-0-15-224.eu-west-1.compute.internal:
      ansible_host: ec2-3-248-211-94.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-3-248-211-94.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-3-248-211-94.eu-west-1.compute.amazonaws.com
    ip-10-0-14-58.eu-west-1.compute.internal:
      ansible_host: ec2-34-255-121-89.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-255-121-89.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-255-121-89.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-6-85.eu-west-1.compute.internal:
      ansible_host: ec2-34-242-169-163.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-5-194.eu-west-1.compute.internal:
      ansible_host: ec2-54-229-245-232.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-9-19.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-43-162.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-14-195.eu-west-1.compute.internal:
      ansible_host: ec2-34-253-228-235.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-8-171.eu-west-1.compute.internal:
      ansible_host: ec2-34-253-191-42.eu-west-1.compute.amazonaws.com

