all:
  vars:
    ansible_become: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-12-168.eu-west-1.compute.internal:
      ansible_host: ec2-3-250-91-58.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-9-136.eu-west-1.compute.internal:
      ansible_host: ec2-52-19-137-178.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-19-137-178.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-19-137-178.eu-west-1.compute.amazonaws.com
    ip-10-0-8-31.eu-west-1.compute.internal:
      ansible_host: ec2-54-216-184-61.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-216-184-61.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-216-184-61.eu-west-1.compute.amazonaws.com
    ip-10-0-7-206.eu-west-1.compute.internal:
      ansible_host: ec2-34-245-192-219.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-245-192-219.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-245-192-219.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-13-136.eu-west-1.compute.internal:
      ansible_host: ec2-34-240-237-65.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-5-14.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-222-94.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-4-239.eu-west-1.compute.internal:
      ansible_host: ec2-54-74-195-244.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-1-244.eu-west-1.compute.internal:
      ansible_host: ec2-54-155-146-219.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-1-223.eu-west-1.compute.internal:
      ansible_host: ec2-34-242-51-244.eu-west-1.compute.amazonaws.com

