all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-6-215.eu-west-1.compute.internal:
      ansible_host: ec2-34-250-23-134.eu-west-1.compute.amazonaws.com
    ip-10-0-14-8.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-95-73.eu-west-1.compute.amazonaws.com
    ip-10-0-4-135.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-117-127.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-0-174.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-233-84.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-244-233-84.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-244-233-84.eu-west-1.compute.amazonaws.com
    ip-10-0-13-98.eu-west-1.compute.internal:
      ansible_host: ec2-34-243-245-131.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-243-245-131.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-243-245-131.eu-west-1.compute.amazonaws.com
    ip-10-0-10-135.eu-west-1.compute.internal:
      ansible_host: ec2-54-217-162-148.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-217-162-148.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-217-162-148.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-12-140.eu-west-1.compute.internal:
      ansible_host: ec2-46-137-16-129.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-12-146.eu-west-1.compute.internal:
      ansible_host: ec2-52-215-88-151.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-5-133.eu-west-1.compute.internal:
      ansible_host: ec2-54-78-249-125.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-4-117.eu-west-1.compute.internal:
      ansible_host: ec2-34-241-150-149.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-10-125.eu-west-1.compute.internal:
      ansible_host: ec2-34-250-206-216.eu-west-1.compute.amazonaws.com

