all:
  vars:
    ansible_become: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-6-176.eu-west-1.compute.internal:
      ansible_host: ec2-34-254-240-239.eu-west-1.compute.amazonaws.com
    ip-10-0-7-127.eu-west-1.compute.internal:
      ansible_host: ec2-3-252-79-216.eu-west-1.compute.amazonaws.com
    ip-10-0-10-128.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-251-59.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-15-31.eu-west-1.compute.internal:
      ansible_host: ec2-52-208-147-106.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-208-147-106.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-208-147-106.eu-west-1.compute.amazonaws.com
    ip-10-0-5-52.eu-west-1.compute.internal:
      ansible_host: ec2-52-211-151-110.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-211-151-110.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-211-151-110.eu-west-1.compute.amazonaws.com
    ip-10-0-6-101.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-34-243.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-3-249-34-243.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-3-249-34-243.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-5-23.eu-west-1.compute.internal:
      ansible_host: ec2-54-216-175-236.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-0-162.eu-west-1.compute.internal:
      ansible_host: ec2-54-78-243-180.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-14-102.eu-west-1.compute.internal:
      ansible_host: ec2-34-247-47-218.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-14-144.eu-west-1.compute.internal:
      ansible_host: ec2-34-253-186-13.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-7-16.eu-west-1.compute.internal:
      ansible_host: ec2-52-213-33-22.eu-west-1.compute.amazonaws.com

