all:
  vars:
    ansible_become: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-8-41.eu-west-1.compute.internal:
      ansible_host: ec2-34-253-196-49.eu-west-1.compute.amazonaws.com
    ip-10-0-0-202.eu-west-1.compute.internal:
      ansible_host: ec2-54-74-228-66.eu-west-1.compute.amazonaws.com
    ip-10-0-10-202.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-9-83.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-12-97.eu-west-1.compute.internal:
      ansible_host: ec2-79-125-78-231.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-79-125-78-231.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-79-125-78-231.eu-west-1.compute.amazonaws.com
    ip-10-0-13-149.eu-west-1.compute.internal:
      ansible_host: ec2-34-245-86-239.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-245-86-239.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-245-86-239.eu-west-1.compute.amazonaws.com
    ip-10-0-3-141.eu-west-1.compute.internal:
      ansible_host: ec2-63-32-108-95.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-63-32-108-95.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-63-32-108-95.eu-west-1.compute.amazonaws.com
    ip-10-0-7-177.eu-west-1.compute.internal:
      ansible_host: ec2-54-217-165-154.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-217-165-154.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-217-165-154.eu-west-1.compute.amazonaws.com
    ip-10-0-10-158.eu-west-1.compute.internal:
      ansible_host: ec2-54-170-57-231.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-170-57-231.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-170-57-231.eu-west-1.compute.amazonaws.com
    ip-10-0-8-65.eu-west-1.compute.internal:
      ansible_host: ec2-34-246-185-147.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-246-185-147.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-246-185-147.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-15-69.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-198-97.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-8-128.eu-west-1.compute.internal:
      ansible_host: ec2-34-247-70-125.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-13-9.eu-west-1.compute.internal:
      ansible_host: ec2-54-194-238-165.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-10-146.eu-west-1.compute.internal:
      ansible_host: ec2-34-242-151-155.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-6-27.eu-west-1.compute.internal:
      ansible_host: ec2-63-32-105-94.eu-west-1.compute.amazonaws.com

