all:
  vars:
    ansible_become: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-8-60.eu-west-1.compute.internal:
      ansible_host: ec2-52-49-144-142.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-9-231.eu-west-1.compute.internal:
      ansible_host: ec2-54-77-118-79.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-77-118-79.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-77-118-79.eu-west-1.compute.amazonaws.com
    ip-10-0-4-66.eu-west-1.compute.internal:
      ansible_host: ec2-34-242-138-201.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-242-138-201.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-242-138-201.eu-west-1.compute.amazonaws.com
    ip-10-0-12-75.eu-west-1.compute.internal:
      ansible_host: ec2-18-203-159-83.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-18-203-159-83.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-18-203-159-83.eu-west-1.compute.amazonaws.com
    ip-10-0-0-27.eu-west-1.compute.internal:
      ansible_host: ec2-3-252-107-96.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-3-252-107-96.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-3-252-107-96.eu-west-1.compute.amazonaws.com
    ip-10-0-12-187.eu-west-1.compute.internal:
      ansible_host: ec2-52-49-229-235.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-49-229-235.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-49-229-235.eu-west-1.compute.amazonaws.com
    ip-10-0-2-220.eu-west-1.compute.internal:
      ansible_host: ec2-34-241-37-98.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-241-37-98.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-241-37-98.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-15-193.eu-west-1.compute.internal:
      ansible_host: ec2-54-170-50-161.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-8-61.eu-west-1.compute.internal:
      ansible_host: ec2-18-203-255-121.eu-west-1.compute.amazonaws.com

