all:
  vars:
    ansible_become: true
    ansible_become_localhost: false
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ssl_enabled: true
    ansible_ssh_private_key_file: /Users/imayat/.ssh/imayat-ireland-bootcamp.pem
    ansible_user: ubuntu

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-1-217.eu-west-1.compute.internal:
      ansible_host: ec2-34-254-252-100.eu-west-1.compute.amazonaws.com
    ip-10-0-11-72.eu-west-1.compute.internal:
      ansible_host: ec2-63-32-100-183.eu-west-1.compute.amazonaws.com
    ip-10-0-4-92.eu-west-1.compute.internal:
      ansible_host: ec2-34-242-96-84.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-11-174.eu-west-1.compute.internal:
      ansible_host: ec2-34-241-82-36.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-241-82-36.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-241-82-36.eu-west-1.compute.amazonaws.com
    ip-10-0-7-53.eu-west-1.compute.internal:
      ansible_host: ec2-34-245-171-115.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-245-171-115.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-245-171-115.eu-west-1.compute.amazonaws.com
    ip-10-0-13-62.eu-west-1.compute.internal:
      ansible_host: ec2-34-248-191-237.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-248-191-237.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-248-191-237.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-2-77.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-76-22.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:

kafka_connect:
  vars:
    # An example of how to install connectors, from Confluent Hub
    # Using CP Ansible
    kafka_connect_confluent_hub_plugins:
      - confluentinc/kafka-connect-datagen:0.6.0

  hosts:
    ip-10-0-1-119.eu-west-1.compute.internal:
      ansible_host: ec2-52-209-66-207.eu-west-1.compute.amazonaws.com

ksql:
  hosts:

control_center:
  hosts:
    ip-10-0-12-90.eu-west-1.compute.internal:
      ansible_host: ec2-34-246-163-167.eu-west-1.compute.amazonaws.com

