all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-7-151.eu-west-1.compute.internal:
      ansible_host: ec2-54-74-231-168.eu-west-1.compute.amazonaws.com
    ip-10-0-8-148.eu-west-1.compute.internal:
      ansible_host: ec2-3-248-182-101.eu-west-1.compute.amazonaws.com
    ip-10-0-12-105.eu-west-1.compute.internal:
      ansible_host: ec2-18-203-159-203.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-11-244.eu-west-1.compute.internal:
      ansible_host: ec2-54-155-173-175.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-155-173-175.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-155-173-175.eu-west-1.compute.amazonaws.com
    ip-10-0-15-73.eu-west-1.compute.internal:
      ansible_host: ec2-34-241-196-129.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-241-196-129.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-241-196-129.eu-west-1.compute.amazonaws.com
    ip-10-0-12-214.eu-west-1.compute.internal:
      ansible_host: ec2-34-242-127-24.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-242-127-24.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-242-127-24.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-10-250.eu-west-1.compute.internal:
      ansible_host: ec2-52-213-56-236.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-4-49.eu-west-1.compute.internal:
      ansible_host: ec2-52-31-214-109.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-3-80.eu-west-1.compute.internal:
      ansible_host: ec2-3-252-52-209.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-8-194.eu-west-1.compute.internal:
      ansible_host: ec2-34-254-240-33.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-14-201.eu-west-1.compute.internal:
      ansible_host: ec2-34-253-186-118.eu-west-1.compute.amazonaws.com

