all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-10-0-2-95.eu-west-1.compute.internal:
      ansible_host: ec2-34-244-164-253.eu-west-1.compute.amazonaws.com
    ip-10-0-14-112.eu-west-1.compute.internal:
      ansible_host: ec2-34-254-203-89.eu-west-1.compute.amazonaws.com
    ip-10-0-3-77.eu-west-1.compute.internal:
      ansible_host: ec2-54-216-139-227.eu-west-1.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-0-0-227.eu-west-1.compute.internal:
      ansible_host: ec2-52-210-254-104.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-210-254-104.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-210-254-104.eu-west-1.compute.amazonaws.com
    ip-10-0-0-87.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-94-119.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-3-249-94-119.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-3-249-94-119.eu-west-1.compute.amazonaws.com
    ip-10-0-2-173.eu-west-1.compute.internal:
      ansible_host: ec2-52-208-6-91.eu-west-1.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-208-6-91.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-208-6-91.eu-west-1.compute.amazonaws.com

schema_registry:
  hosts:
    ip-10-0-12-139.eu-west-1.compute.internal:
      ansible_host: ec2-3-249-109-117.eu-west-1.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-10-0-5-112.eu-west-1.compute.internal:
      ansible_host: ec2-54-171-253-92.eu-west-1.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-10-0-1-20.eu-west-1.compute.internal:
      ansible_host: ec2-34-253-79-122.eu-west-1.compute.amazonaws.com

ksql:
  hosts:
    ip-10-0-13-186.eu-west-1.compute.internal:
      ansible_host: ec2-18-202-239-139.eu-west-1.compute.amazonaws.com

control_center:
  hosts:
    ip-10-0-13-161.eu-west-1.compute.internal:
      ansible_host: ec2-54-194-119-87.eu-west-1.compute.amazonaws.com

